const indianStates = <String>[
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
];

const polytechnicColleges = <String>[
  'Govt. Polytechnic Kangra',
  'Government Polytechnic Hamirpur',
  'Government Polytechnic Sundernagar',
  'Government Polytechnic Rohru',
  'Government Polytechnic Kinnaur',
  'Government Polytechnic Banikhet',
  'Government Polytechnic Kullu',
  'Government Polytechnic Paonta Sahib',
  'Government Polytechnic Bilaspur',
  'Government Polytechnic Chamba',
  'Government Polytechnic Talwar',
  'Government Polytechnic Ambota',
  'Government Polytechnic College Una',
  'Government Polytechnic College Solan',
  'Government Polytechnic College Mandi',
  'Government Polytechnic College Nalagarh',
  'Government Polytechnic College Lahaul and Spiti',
  'Government Millennium Polytechnic Chamba',
  'Atal Bihari Vajpayee Government Institute of Engineering and Technology Pragatinagar',
  'Rajiv Gandhi Government Polytechnic College Banikhet',
  'Government Polytechnic College for Women Kandaghat',
  'Government Polytechnic for Women Faridabad',
  'Government Polytechnic Ambala City',
  'Government Polytechnic Nilokheri',
  'Government Polytechnic Sonipat',
  'Government Polytechnic Hisar',
  'Government Polytechnic Sirsa',
  'Government Polytechnic Manesar',
  'Government Polytechnic Education Society Uttawar',
  'Mehr Chand Polytechnic College Jalandhar',
  'Government Polytechnic College Amritsar',
  'Government Polytechnic College Bathinda',
  'Government Polytechnic College Ludhiana',
  'Government Polytechnic College Patiala',
  'Government Polytechnic College Khoonimajra',
  'Pusa Institute of Technology Delhi',
  'Aryabhatt Institute of Technology Delhi',
  'Guru Nanak Dev Institute of Technology Delhi',
  'Ambedkar Institute of Technology Delhi',
  'Government Polytechnic Dehradun',
  'Government Polytechnic Srinagar Garhwal',
  'Government Polytechnic Kashipur',
  'Government Polytechnic Nainital',
  'Government Polytechnic Pithoragarh',
  'Government Polytechnic Lucknow',
  'Government Polytechnic Kanpur',
  'Government Polytechnic Ghaziabad',
  'Government Polytechnic Gorakhpur',
  'Government Polytechnic Jhansi',
  'Government Polytechnic Jaipur',
  'Government Polytechnic College Ajmer',
  'Government Polytechnic College Jodhpur',
  'Government Polytechnic College Kota',
  'Government Polytechnic Ahmedabad',
  'Government Polytechnic Gandhinagar',
  'Government Polytechnic Rajkot',
  'Government Polytechnic Vadodara',
  'Government Polytechnic Mumbai',
  'Government Polytechnic Pune',
  'Government Polytechnic Nagpur',
  'Government Polytechnic Nashik',
  'S V Polytechnic College Bhopal',
  'Government Polytechnic College Indore',
  'Government Polytechnic College Jabalpur',
  'Government Polytechnic College Raipur',
  'Government Polytechnic College Durg',
  'Government Polytechnic Ranchi',
  'Government Polytechnic Dhanbad',
  'Government Polytechnic Bhubaneswar',
  'Government Polytechnic Cuttack',
  'Government Polytechnic Kolkata',
  'Central Calcutta Polytechnic',
  'Government Polytechnic Patna',
  'Government Polytechnic Muzaffarpur',
  'Government Polytechnic Guwahati',
  'Government Polytechnic Shillong',
  'Government Polytechnic Agartala',
  'Government Polytechnic Aizawl',
  'Government Polytechnic Kohima',
  'Government Polytechnic Imphal',
  'Government Polytechnic Itanagar',
  'Government Polytechnic Bengaluru',
  'Government Polytechnic Mangalore',
  'Government Polytechnic Mysuru',
  'Government Polytechnic Chennai',
  'Central Polytechnic College Chennai',
  'Government Polytechnic College Coimbatore',
  'Government Polytechnic Hyderabad',
  'Government Polytechnic Warangal',
  'Government Polytechnic Vijayawada',
  'Government Polytechnic Visakhapatnam',
  'Government Polytechnic College Kalamassery',
  'Government Polytechnic College Kozhikode',
  'Government Polytechnic College Thrissur',
  'Government Polytechnic Panaji',
  'Government Polytechnic Daman',
  'Government Polytechnic Port Blair',
  'Government Polytechnic Leh',
  'Government Polytechnic Jammu',
  'Government Polytechnic Srinagar',
  'Government Polytechnic Puducherry',
];
