USE e-PolyPariksha HP;

-- DBA pattern: import students from an external student database into e-PolyPariksha HP auth.
-- Replace external_student_db with the DBA-managed database name.
-- Password hashes must be generated by the DBA/app tooling; never insert plaintext passwords.

INSERT INTO users (full_name, college_id, password_hash, role, branch_id, is_active)
SELECT
  s.full_name,
  s.college_id,
  s.password_hash,
  'student',
  b.id,
  TRUE
FROM external_student_db.students s
JOIN branches b ON b.code = s.branch_code
ON DUPLICATE KEY UPDATE
  full_name = VALUES(full_name),
  password_hash = VALUES(password_hash),
  branch_id = VALUES(branch_id),
  is_active = VALUES(is_active);
